### ISSUE TITLE
Change event not fired

### ISSUE THREAD

**Issue by mebibou** [ngx-toggle/ngx-toggle#13]
### Bug description:
When binding to `(change)` event, nothing happens. It should be triggered when the user toggles the component.
This should be different from `(valueChange)` event which triggers even when loading the component, which is not what should happen for `(change)` event.

For example, with a form like this:
```
<input [(ngModel)]="user.firstName" (change)="onFirstNameChanged($event)" />

<ng-toggle [(ngModel)]="user.admin" (valueChange)="onAdminChanged($event)"></ng-toggle>
```

In this example, when loading the page with `user = {firstName: 'first', admin: true}`, `onFirstNameChanged` will not be fired but `onAdminChanged` will. Now if we use `(change)` on `ng-toggle` instead, it should also not fire unless the user changes the model by interacting with the component.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.2

ng-bootstrap: 4.0.2

Bootstrap: 4.3.1

**Comment by trickeyone** [comment]
Weird, I hadn't seen it do that before, but I see what you mean. I'll address it in the next release. Thanks for the find!

Side-note: It's not designed to fire on the `(change)` output, that's why you're not seeing it fire. The only output that the component has is `(valueChanged)`.  From what I can tell, if you include the `FormsModule` it'll support the `(change)` output on most components, even if they don't use it.
