### ISSUE TITLE
Inital value animation

### ISSUE THREAD

**Issue by istibekesi** [ngx-toggle/ngx-toggle#14]
Is there a way to skip the initial animation, right after rendering the toggle?

Example:
https://stackblitz.com/edit/angular-gp2fyk
Usually, values are loaded asynchronously, so this quick movement is not desired.

**Comment by istibekesi** [comment]
@trickeyone 
Thanks for the fix. 
However, `disableInitialAnimation` now breaks the animation, unless you click on the handle. 

![handle(1)_edit_0_edit_0](https://user-images.githubusercontent.com/5990010/67777988-de9bc400-fa62-11e9-8b95-b81c992e2064.gif)

**Comment by trickeyone** [comment]
I've been able to fix it. I will caution one thing, though. When disabling the initial animation, you'll see some blocky-ness when the component is first rendered. This is due to having to calculate the widths of the two labels. This is necessary because we have to know the widest part to be able to properly display all of the labels properly. So, I don't know if this is going to 100% what you're looking for.
